FROM debian:stable-slim

RUN apt-get update && apt-get install -y \
    iproute2 iputils-ping net-tools tcpdump bridge-utils iptables

COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

CMD ["/startup.sh"]