FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    iproute2 iputils-ping net-tools bridge-utils \
    tcpdump \
    prometheus-node-exporter

COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

CMD ["/startup.sh"]